### ISSUE TITLE
Long Press | Button | Move key to Lock ctl key from being active

### ISSUE THREAD

**Issue by GoogleCodeExporter** [klausw/hackerskeyboard#445] opened 2016-01-22 21:46 UTC
```
[ Before posting bugs, please check
https://code.google.com/p/hackerskeyboard/wiki/FrequentlyAskedQuestions and
the existing bugs for known issues - my responses may be delayed since I
have very little time to work on this project. ]

What steps will reproduce the problem?
1.type really fast
2.accidentally hit ctl
3.delete everything by hitting another key

What is the expected behavior? Data typed doesn't get lost.
What do you see instead? Data gets highlighted then deleted once the 'any key' 
is pressed :(

What version of Hacker's Keyboard are you using, for example "1.37"? 1.37.1419..

On what phone or tablet? asus padfone X

If applicable, does this affect the 4-row or 5-row layout, or both? Which
language(s)? Both / All with ctl key.

Please provide any additional information below.

Please fix, its exaspersting!
```

Original issue reported on code.google.com by `Andrew.P...@gmail.com` on 13 Dec 2014 at 1:26

**Comment by klausw** [comment] 2016-10-22 21:39
Duplicate of issue #487, this is fixed in v1.39.1 alpha.

**Closed by klausw** 2016-10-22 21:39 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
