### ISSUE TITLE
battry drain

### ISSUE THREAD

**Issue by Zero-Sploit** [klausw/hackerskeyboard#828] opened 2020-10-24 17:09 UTC
the app runs consantly in the background  and drains the battery reinstalling doesnt work

**Comment by klausw** [comment] 2020-10-24 17:21
It's normal to be listed as a background app since input methods are
services. It shouldn't use a noticeable amount of CPU time or battery
unless it's being actively used though. Do you have a screenshot or battery
usage report showing it as the cause?

**Comment by Zero-Sploit** [comment] 2020-10-26 03:15
i do not have a screen shot or battery usage report showing it as the cause. i will post a screen shot if it happens again.

**Comment by Zero-Sploit** [comment] 2020-10-26 13:27
here is a screen shot 
![6811188965346773651](https://user-images.githubusercontent.com/51815198/97178110-6e0aae80-176d-11eb-84b2-e1ce43f7c7e8.png)

**Comment by klausw** [comment] 2020-10-26 16:44
Thank you for posting. Unfortunately I don't have a good way to narrow down what's causing the issue - I haven't seen it misbehave like this on my own devices.

Would you mind sharing your phone type and OS version? It's possible that there's a strange interaction with the system on some devices.

Also, could you check the Android settings > Battery > Details view to see if that also shows the keyboard as a main battery consumer? It may be in the three-dots menu depending on your Android version. I think there's still a possibility that the "smart cleaning" app is confused and the battery drain is actually caused by something else, but if it's confirmed it seems that the keyboard isn't compatible with your device.

**Comment by Zero-Sploit** [comment] 2020-10-26 17:09
i have an LG running android 9. i didn't see any thing stating that the app was draining the battery in  settings > Battery > Details so maybe its just smart clean getting confused like you stated.

**Comment by klausw** [comment] 2020-10-26 18:40
Thanks for the response. I'll close this as not reproducible for now, but if you (or anyone else reading this) has more details that specifically point to the keyboard draining battery, please add an update.

**Closed by klausw** 2020-10-26 18:40 UTC
