### ISSUE TITLE
ctrl + while typing ... gets u p.off

### ISSUE THREAD

**Issue by GoogleCodeExporter** [klausw/hackerskeyboard#417] opened 2016-01-22 21:46 UTC
```
[ Before posting bugs, please check
https://code.google.com/p/hackerskeyboard/wiki/FrequentlyAskedQuestions and
the existing bugs for known issues - my responses may be delayed since I
have very little time to work on this project. ]

What steps will reproduce the problem?
1. ctrl+a
2. see not marked text, overwrite. no undo.
3. pissed off again...

What is the expected behavior? What do you see instead?

What version of Hacker's Keyboard are you using, for example "1.37"? (See
"Debug" section at the bottom of the app's Settings menu.)

1.37

On what phone or tablet?

tablet

If applicable, does this affect the 4-row or 5-row layout, or both? Which
language(s)?

5row

Please provide any additional information below.


a way to disable this insane funktokn or give it an undo!

written more then one time to klausw@google.com but dont get reply
whats he doing

```

Original issue reported on code.google.com by `crap...@googlemail.com` on 6 Jun 2014 at 6:22

**Comment by klausw** [comment] 2016-10-22 21:38
Duplicate of issue #487, this is fixed in v1.39.1 alpha.

**Closed by klausw** 2016-10-22 21:38 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
