### ISSUE TITLE
Completions not visible (packs installed, semiauto typing works)

### ISSUE THREAD

**Issue by Cigaes** [klausw/hackerskeyboard#936] opened 2023-12-29 14:28 UTC
Hi.

I installed Hacker's Keyboard (1.40.7 official) and completions pack (en and fr) from the Play store, but the completions are not showing up, the line above the keyboard stays desperately black.

I know the completions packs are detected, because if I enable semiautomatic typing, “Bonj” causes the space bar to light orange and pressing it completes into ”Bonjour”. Even though ”Bonjour” was never shown.

![Screenshot_20231229-152329_Trebuchet](https://github.com/klausw/hackerskeyboard/assets/5101943/a02c4b5c-1bcc-4e75-ad7d-a8fb0a85e5a3)
![Screenshot_20231229-152354_Trebuchet](https://github.com/klausw/hackerskeyboard/assets/5101943/a1bd9368-6ee2-4223-beee-496fac6944c5)
![Screenshot_20231229-152408_Trebuchet](https://github.com/klausw/hackerskeyboard/assets/5101943/310001a6-2a3b-4f90-b567-c410b45a4dad)
![Screenshot_20231229-152422_Trebuchet](https://github.com/klausw/hackerskeyboard/assets/5101943/b9b36bab-4cca-4f85-8a07-2b7491ed1074)
![Screenshot_20231229-152443_Trebuchet](https://github.com/klausw/hackerskeyboard/assets/5101943/ef90055a-b3d3-406f-aeb3-1ff3f457fefa)
![Screenshot_20231229-152450_Trebuchet](https://github.com/klausw/hackerskeyboard/assets/5101943/9e57771a-2680-41dd-a807-23e350f9980c)

I have an older phone with version 1.41.1 custom from F-Droid and language packs from Play where it works. I tried on the new phone with the F-Droid version too, without success.

**Comment by asl97** [comment] 2023-12-29 16:35
Pressing space actually select the first suggestion, it just that the suggestions row is broken on newer android version, making this issue technically a duplicate of #901

**Comment by Cigaes** [comment] 2024-01-28 10:08
Thanks, I had not found this issue.

**Closed** 2024-01-28 10:08 UTC
