### ISSUE TITLE
Keep accidentally erasing text by hitting Control A

### ISSUE THREAD

**Issue by GoogleCodeExporter** [klausw/hackerskeyboard#311] opened 2016-01-22 21:45 UTC
```
I'll be typing a long email, and I accidentally erase the whole thing by fat 
fingering Control A. Since there's no Undo in most applicstions, this results 
in permanent erasure of important text. For now, I'm switching back to the 
default Samsung keyboard which doesn't present a Control key.

Specs:

* Android 4.0.4 Ice Cream Sandwich
* Samsung Galaxy SIII
* T-Mobile
```

Original issue reported on code.google.com by `andrew.p...@gmail.com` on 17 Nov 2012 at 4:44

**Comment by klausw** [comment] 2016-10-22 21:38
Duplicate of issue #487, this is fixed in v1.39.1 alpha.

**Closed by klausw** 2016-10-22 21:38 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
