### ISSUE TITLE
Option to disable ^A

### ISSUE THREAD

**Issue by GoogleCodeExporter** [klausw/hackerskeyboard#43] opened 2016-01-22 21:41 UTC
```
What steps will reproduce the problem?
1. Type text, occassionally hit old-fashioned position Ctrl & A together, and 
clobber partial word.
2. Become annoyed.

What is the expected output? What do you see instead?
Just an "a"

What version of the product are you using? On what operating system?
Android 3.0.1

Please provide any additional information below.


```

Original issue reported on code.google.com by `belg4...@gmail.com` on 29 Jun 2011 at 10:45

**Comment by klausw** [comment] 2016-10-22 21:38
Duplicate of issue #487, this is fixed in v1.39.1 alpha.

**Closed by klausw** 2016-10-22 21:38 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
